-- Example MySQL schema for leaderboard and game results
CREATE TABLE IF NOT EXISTS leaderboard (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(64) NOT NULL,
  score INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS game_results (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(64) NOT NULL,
  game VARCHAR(32) NOT NULL,
  result VARCHAR(32) NOT NULL,
  score INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
